### PR TITLE
[JENKINS-69385] Add logging verbosity configuration

### PR DESCRIPTION
**Pull request by pavlovic-ivan**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
  - a parameter called `logLevel` added to the plugin, so it can be used to  configure log verbosity both in Jenkins UI and console
- [x] Link to relevant issues in GitHub or Jira
  - https://issues.jenkins.io/browse/JENKINS-69385
- [x] Link to relevant pull requests, esp. upstream and downstream changes
  - no other pull requests to provide 
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
  - no tests to provide as the change is not about plugin functionality itself

### CODE REVIEW

**Comment by dave-gantenbein** [comment]
@nilleb - we have a potential solution for this issue: https://issues.jenkins.io/browse/JENKINS-69385

Any chance you could take a look at this PR and give us some feedback? Thanks!

**Comment by nilleb** [comment]
@dave-gantenbein @stackedsax why should it be me? I probably am the default assignee for JIRA issues related to this plugin, I have left no activity on it all.

The maintainer of this plugin is @jetersen - I have no more access to mstest since 2017.

Have a good day,

**Comment by stackedsax** [comment]
@nilleb, no worries, I was just trying to follow the breadcrumbs back to the real owner. Thanks for pointing out @jetersen is the maintainer -- perhaps they can chime in here.

**Comment by pavlovic-ivan** [comment]
Hi @jetersen. This PR has open for a while. Do you maybe have time to review it? It would greatly benefit a project i am working on, and your help here would be greatly appreciated

**Comment by pavlovic-ivan** [comment]
Hi @jetersen. Just a kind reminder if you can take a look at the PR.

All the best!

**Comment by jetersen** [comment]
@pavlovic-ivan
Feel free to follow the [adopt a plugin process](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/)

**Comment by pavlovic-ivan** [comment]
Hi @jetersen , thanks for coming back to me, really appreciate it! I will do as proposed 🙏

**Pull request closed without merging**
